# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serverinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u8d44\u6e90\u540d\u79f0')),
                ('absname', models.CharField(max_length=300, verbose_name='\u8d44\u6e90\u8def\u5f84')),
                ('ftype', models.CharField(max_length=100, verbose_name='\u8d44\u6e90\u7c7b\u578b')),
                ('superid', models.CharField(max_length=300, verbose_name='\u4e0a\u7ea7\u8d44\u6e90id')),
                ('changeflag', models.CharField(blank=True, choices=[('0', '\u6b63\u5e38'), ('1', '\u65b0\u589e'), ('2', '\u53d8\u66f4'), ('3', '\u5220\u9664'), ('4', '\u53d8\u66f4+')], max_length=2, verbose_name='\u53d8\u66f4\u72b6\u6001')),
                ('oldproperty', models.CharField(max_length=100, verbose_name='\u539f\u8d44\u6e90\u5c5e\u6027')),
                ('newproperty', models.CharField(max_length=100, verbose_name='\u65b0\u8d44\u6e90\u5c5e\u6027')),
                ('checkflag', models.CharField(blank=True, choices=[('0', '\u5426'), ('1', '\u662f')], max_length=2, verbose_name='\u662f\u5426\u76d1\u63a7')),
                ('writetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('serverid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverinfo.Serverinfo')),
            ],
            options={
                'verbose_name': '\u8d44\u6e90\u4fe1\u606f',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contentinfo',
            unique_together=set([('absname', 'serverid')]),
        ),
        migrations.AlterIndexTogether(
            name='contentinfo',
            index_together=set([('name',)]),
        ),
    ]
