# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Systeminfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=100, verbose_name='\u53c2\u6570\u540d')),
                ('param_value', models.CharField(max_length=100, verbose_name='\u53c2\u6570\u503c')),
                ('param_display', models.CharField(max_length=100, verbose_name='\u53c2\u6570\u63cf\u8ff0')),
                ('param_type', models.CharField(choices=[(b'1', '\u5e38\u89c4'), (b'2', 'Email'), (b'3', '\u5b9a\u65f6\u4efb\u52a1')], max_length=2, verbose_name='\u53c2\u6570\u7c7b\u578b')),
            ],
            options={
                'permissions': (('browse_systeminfo', '\u6388\u6743\u6d4f\u89c8 \u7cfb\u7edf\u8bbe\u7f6e'),),
                'verbose_name': '\u7cfb\u7edf\u8bbe\u7f6e',
            },
        ),
        migrations.AlterIndexTogether(
            name='systeminfo',
            index_together=set([('id', 'param_name')]),
        ),
    ]
