# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opmodel', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u7c7b\u578b')),
                ('opaction', models.CharField(default='Modify', max_length=40, verbose_name='\u52a8\u4f5c')),
                ('opobject', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5bf9\u8c61')),
                ('writetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u65e5\u5fd7\u4fe1\u606f',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userlog',
            unique_together=set([('id',)]),
        ),
        migrations.AlterIndexTogether(
            name='userlog',
            index_together=set([('id',)]),
        ),
    ]
