# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serverinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u5668\u540d\u79f0')),
                ('ip', models.CharField(max_length=100, verbose_name='IP')),
                ('port', models.CharField(max_length=100, verbose_name='\u7aef\u53e3')),
                ('username', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('password', models.CharField(max_length=100, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('writetime', models.CharField(max_length=100, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u4fe1\u606f',
            },
        ),
        migrations.AlterUniqueTogether(
            name='serverinfo',
            unique_together=set([('ip',)]),
        ),
        migrations.AlterIndexTogether(
            name='serverinfo',
            index_together=set([('name',)]),
        ),
    ]
