var option = {
	title:{
		text:""
	},
	tooltip:{
		show:true,
		showContent:true,
		//triggerOn:"click",
		alwaysShowContent:false,
		enterable:false,
		confine:false,
		position:"right",
		formatter:function(a,b,c){
			if(a.dataType == "node"){
				return a.data.value;
			}
		}
	},

	animationDuration:1200,
	animationEasingUpdate:"quinticInOut",
	backgroundColor:"#fff",
	series:[{
		draggable:true,
		symbol:"circle",
		legendHoverLink:true,
		hoverAnimation:true,
		focusNodeAdjacency:false,
		name:"服务器资源监控系统",
		type:"graph",
		roam:true,
		layout:"force",
		force:{
			repulsion:800,
			gravity:0.1,
			layoutAnimation:true
		},/*
		categories:[
			{
				name:"文件夹"
			},
			{
				name:"文件"
			}
		],*/
		label:{
			normal:{
				show:true,
				position:"bottom",
				//formatter:"{b}"
				textStyle:{
					color:"#333"
				}
			},
			emphasis:{
				textStyle:{
					color:"#333"
				}
			}
		},
		itemStyle:{
			normal:{
				color:"#2f4554"
			}
		},
		lineStyle:{
			normal:{
				width:1,
				curveness:0,
				color:"#ccc",
				opacity:1
			},
			emphasis:{
				width:2
			}
		},
		data:[		],
		links:[]
	}]
}
